version: "3.9"

services:
  web:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: api_service:create_app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app_db
      SECRET_KEY: Dyn4m1cAsS3tKey
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
